name: SpigPass
version: 1.0
main: me.dima.spigpass.spigpass
api-version: 1.17
commands:
  password:
    description: Allows players to enter the server with a password.
    usage: /password <password>
permissions:
  spigpass.use:
    description: Allows players to use the /password command
    default: op
